### PR TITLE
Docker lab blog post

### PR DESCRIPTION
**Pull request by IanMuchina**
Docker lab blog post. Should I buid it? I found no optput folder on the repo

### CODE REVIEW

**Comment by IanMuchina** [comment]
Whoever's building add this between the <head><head/> html tag
```
<link rel=“canonical” href=“https://ianmuchina.com/docker-lab” />
```

**Comment by jasonrogena** [comment]
@IanMuchina Awesome! Looks good. Can't wait to read it.

> Whoever's building add this between the `<head><head/>` html tags
> 
> ```
> <link rel=“canonical” href=“https://ianmuchina.com/docker-lab” />
> ```

@rwanyoike should comment on the best way of doing this. My thinking is since the HTML pages generated when you run `make html` should be considered ephemeral, the changes manually made to the post's header will be overridden when `make` is rerun. Since most posts in this repo are actually cross-posts, maybe we should add this to the template?

**Comment by jasonrogena** [comment]
@IanMuchina so that you're not blocked, you can always add a temporary note on the post linking to the original post. We'll then create an issue in the Pelican repo to add the support for addling the link tag in a post's header. What do you think?

**Comment by IanMuchina** [comment]
Yeah, that should work

**Comment by IanMuchina** [comment]
Should I use the gh- pages or the master branch

**Comment by jasonrogena** [comment]
@IanMuchina master, then we'll build and push to gh-pages.

**Pull request merged**
