### PR TITLE
Add blog post about rotating MySQL slow query logs

### PR DESCRIPTION
**Pull request by oguya**
This post is also available on my personal blog; https://oguya.ch/posts/2016-04-13-safely-rotating-mysql-slow-logs/

### CODE REVIEW

**Comment by rwanyoike** [comment]
Super!

-- 
Raymond

**Comment by jasonrogena** [comment]
@oguya Bruh, your blog s3x as duck

**Comment by urbanslug** [comment]
@jasonrogena It's so hot I'm deleteing mine LOL

**Comment by oguya** [comment]
w00t! Thanks gents!

**Comment by oguya** [comment]
@jasonrogena @urbanslug  I'm using [Hugo](https://gohugo.io/) for static web pages with [vienna theme](http://themes.gohugo.io/vienna/)

**Comment by alanorth** [comment]
Just wanna throw it out there that I've been using [Hugo with vienna](https://alanorth.github.io/cgspace-notes) for six months. ;)

**Comment by rwanyoike** [comment]
@alanorth 👍 for keeping a daily log.

**Comment by nj3ma** [comment]
nice one james. left a comment on your blawg re: common situation - logging has been known to "stop" sometimes  after setting up logrotate. we (OK, maybe just me) want more of these!

**Pull request merged**
