### PR TITLE
Add blog post about BRCK's GPL violation

### PR DESCRIPTION
**Pull request by alanorth**
Think before merging this. We should have a discussion whether this is appropriate for posting on the LUG blog. I don't mind attaching these allegations to my own blog / name, but I can't speak for the LUG as a whole.

Can we get some +1's and -1's here in the comments?

### CODE REVIEW

**Comment by kenju254** [comment]
@alanorth I need write access to merge it. I have read it and its really well done

**Comment by alanorth** [comment]
Oh, @kenju254, you're not a member of the organization? Hang tight...

But before merging, I really want to get a few more people +1 and -1 ... we can't speak for the whole of the LUG on this kinda controversial topic.

**Comment by adamn** [comment]
Looks good to me.  I commented on Mjanja.

**Comment by Brainiarc7** [comment]
This post is valid, well written and factual. I propose a merge.

**Comment by kenju254** [comment]
@alanorth I am not kindly add .. makes it 3

**Comment by alanorth** [comment]
Thanks for the comments, @adamn. I responded to your comment on Mjanja.

**Comment by jasonrogena** [comment]
Looks good. Merge it.. If the GPL 'was misinterpreted' we can always amend. I'll update the meetup post (now that BRCK replied)

**Comment by kenju254** [comment]
@alanorth I think we have 4  is that enough for a merge

**Comment by oguya** [comment]
After carefully reading & understanding this blog post, I believe it is correct & worthy to be merged! :+1:

**Comment by eebrah** [comment]
+1

**Comment by Brainiarc7** [comment]
I'm also not a member of the organization...

**Comment by urbanslug** [comment]
+1 all the things

**Comment by alanorth** [comment]
Thanks for the +1's. @kenju254 and @Brainiarc7 I've sent you invites to join the nairobilug organization on GitHub.

Also, please don't offer to merge this post unless you also know how to update the blog (`gh-pages`). ;)

**Comment by JohnTroony** [comment]
+1 :bowtie:

**Pull request merged**
