### PR TITLE
Add code of conduct

### PR DESCRIPTION
**Pull request by BonfaceKilz**
Add Code of Conduct. Instead of creating a page, just have a link that points to the md file on GH. Wdyt?

### CODE REVIEW

**Comment by BonfaceKilz** [comment]
Address #183

**Comment by rwanyoike** [comment]
Finally!! A Code of Conduct for the group helps ensure the safety and comfort of all participants, and now we can have one.

Thank you @BonfaceKilz for this contribution.

**Comment by jasonrogena** [comment]
Should we do anything with the comments added in https://github.com/nairobilug/nairobilug.or.ke/pull/157, which I believe is related?

**Comment by BonfaceKilz** [comment]
Jason Rogena ***@***.***> aliandika:

> Should we do anything with the comments added in https://github.com/nairobilug/nairobilug.or.ke/pull/157, which I believe is related?
>

Hmmmm.  Then have a vote as earlier suggested?
Question now becomes how to make that vote.  More
on this later.

The main argument against the CoC is that it
doesn't do much to protect the organisation from
bad actors.  IOW, no meaningful change: In Orth's
words: "What good does writing down 'don't be a
jerk' do?".  An argument was made that joining the
LUG "is driven by personal interest rather than
comfort of knowing whatever else is out there".
Also it adds administrative loads on the LUG.

OTOH, the main proponents of a CoC are mainly
considering new-comers and people with varying
levels of confidence; make them feel "safe"
despite being driven by personal interest.  Many
people in this space are used to "jerks", and few
call them out IMHO (my opinions - I may be wrong
here).

I want to either close or merge this PR:
https://github.com/nairobilug/nairobilug.or.ke/pull/157
once and for all.  That said, let's vote.  Reply
to this thread with a +1 or -1 for a code of
conduct - your commentary is also welcome (just be
polite \m/\m/).  I'll leave this going on for the
weekend and tally things on Monday.  After all, I
think it best for the community to make that
choice ;)

Personally, I vote +1; so that's one vote for the
pro-CoCs.

PS: I have the github issue Cc'ed so please do a
wide-reply so that comments also reflect on GH.

-- 
(Life is like a pencil that will surely run out,
    but will leave the beautiful writing of life.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Comment by BonfaceKilz** [comment]
+1 on having a CoC.

**Comment by BonfaceKilz** [comment]
Going ahead to close this.  This has been addressed in:

- https://github.com/nairobilug/nairobilug.or.ke/commit/14988d588ea0f5dd5a728eb97c72432f275d1973
- https://github.com/nairobilug/nairobilug.or.ke/commit/1e478c10ca16e225da0a18ae885d81ca0b317dd1

**Comment by BonfaceKilz** [comment]
Should probably reevaluate mission statement first. This:
https://nairobilug.or.ke/pages/about-us.html
needs to be updated. The aim should be to create a positive environment 
that enables attainment of the Nairobi LUG mission statement.

**Pull request closed without merging**
