### PR TITLE
Add blog post about PostgreSQL on Mac OS X

### PR DESCRIPTION
**Pull request by alanorth**
Also posted on my blog, re-posted for posterity: https://mjanja.ch/2016/04/using-homebrews-postgresql-mac-os-x/

### CODE REVIEW

**Comment by alanorth** [comment]
Muchas gracias, señor. :clap:

**Comment by urbanslug** [comment]
I have a thing or two say on this :smile: e.g how I to delete everything after setting up in case I feel what I set up didn't go quite right? I guess I could also RTFM.

**Comment by alanorth** [comment]
Depends on how much "everything" you want to delete. You can just stop postgres, `rm -rf /opt/brew/var/postgres/*`, then init all over again. :smile:

**Comment by urbanslug** [comment]
@alanorth That's probably it (what I want) I want to roll back to a fresh postgres install.

hmm what of setting up a vargrant or docker VM which has a linux env that you know and love and connect to that, does that make sense?

**Comment by alanorth** [comment]
Vagrant is a tool that uses VirtualBox to make VMs. It's annoying compared to the native tools you get in GNU/Linux, like systemd-nspawn and KVM and libvirt.

I hate Docker. It is literally lightweight Linux containers (cgroups). There is literally no Docker on Mac OS X, because it's impossible. "Docker on Mac OS X" is actually a Linux virtual machine in VirtualBox on Mac OS X, which is fucking retarded.

**Comment by rwanyoike** [comment]
Trying out postgres using docker would be simple:

```shell
# Pull postgress image (online)
docker pull postgres
# Start postgres container
docker run -e POSTGRES_PASSWORD=hackme -d postgres
```

You'd have the postgres available (`docker ps`) :100:. If you got fed up and needed to start over:

```shell
# Stop postgres container
docker stop <CONTAINER_ID>
# Start postgres container
docker run -e POSTGRES_PASSWORD=mehack -d postgres
```

**Comment by urbanslug** [comment]
@rwanyoike So you think it's a good idea to run postgres via docker, right?
 I understand @alanorth 's concerns but Macs are terrible for these things.

**Comment by rwanyoike** [comment]
@urbanslug yes.

I personally don't install db's, web servers, services etc on my laptop. I isolate them (docker, vagrant etc). Keeps them clean, consistent, easy to move (mac -> linux), easy to remove. 

I don't mind, I use virtualbox on a regular basis. :ok_hand:

**Pull request merged**
