### PR TITLE
Issue 114 making chapos

### PR DESCRIPTION
**Pull request by highPriestLOL**
Update chapo maker

### CODE REVIEW

**Comment by alanorth** [comment]
I don't even know what you did, but you are somehow mixing pull requests... now commits for the chapo stuff are here in the fluidbox pull request.

**Comment by highPriestLOL** [comment]
I switched to master prolly needed to hard reset or something. Now I can't even revert, which apparently, should be possible to revert pull requests https://help.github.com/articles/reverting-a-pull-request/

Will leave this pull requesting and merging business for now.

**Comment by alanorth** [comment]
Don't be dismayed! You're making good progress. Assuming the LUG's repo is
in the `lug` remote:

```
git checkout master
git remote update lug
git reset --hard lug/master
```

Then do all your work on topic branches, based on master:

```
git checkout -b some-feature master
git commit
git push anthony some-feature
```

Then you can make a pull request on GitHub, from `anthony/some-feature`
into `lug/master`.

On Tue, Feb 17, 2015 at 12:00 AM, Anthony Oduor <notifications@github.com>
wrote:

> I switched to master prolly needed to hard reset or something. Now I can't
> even revert, which apparently, should be possible to revert pull requests
> https://help.github.com/articles/reverting-a-pull-request/
>
> Will leave this pull requesting and merging business for now.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/nairobilug/nairobilug.or.ke/pull/117#issuecomment-74571680>
> .
>



-- 
Alan Orth
alan.orth@gmail.com
https://alaninkenya.org
https://mjanja.ch
"In heaven all the interesting people are missing." -Friedrich Nietzsche
GPG public key ID: 0x8cb0d0acb5cd81ec209c6cdfbd1a0e09c2f836c0

**Comment by alanorth** [comment]
Don't be dismayed! You're making good progress. Assuming the LUG's repo is
in the `lug` remote:

```
git checkout master
git remote update lug
git reset --hard lug/master
```

Then do all your work on topic branches, based on master:

```
git checkout -b some-feature master
git commit
git push anthony some-feature
```

Then you can make a pull request on GitHub, from `anthony/some-feature`
into `lug/master`.

**Comment by oguya** [comment]
@highPriestLOL  should we close this pull request so that you can re-submit multiple atomic ones ?

**Comment by highPriestLOL** [comment]
@oguya Sure, close it.

**Pull request closed without merging**
