### PR TITLE
Add a Code of Conduct page

### PR DESCRIPTION
**Pull request by rwanyoike**
> We want a productive happy community that can welcome new ideas

Borrowed from creative common sources:
- Ubuntu Code of Conduct 2.0 http://www.ubuntu.com/about/about-ubuntu/conduct
- antiharassment policy at the Geek Feminism Wiki http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy
- https://gtalug.org/about/code-of-conduct/

Related to #153

### CODE REVIEW

**Comment by rwanyoike** [comment]
As this is a big subject on it's own, this pull request probably needs a vote, as it affects all members.

**Comment by urbanslug** [comment]
@rwanyoike This is great! This is really good for community.

**Comment by netivity** [comment]
C.o.Cs are mostly bullshit. I vote no.

On 6/30/16, Njagi Mwaniki <notifications@github.com> wrote:
> @rwanyoike This is great! This is really good for community.
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nairobilug/nairobilug.or.ke/pull/157#issuecomment-229862875


-- 
Mwaoshe Njemah
Lead,
Teke Teke
www.teketeke.co.ke
moshe@teketeke.co.ke
0722 99 19 18 | 0733 66 55 77

**Comment by alanorth** [comment]
I lean towards **no** too. With and without a Code of Conduct we will have good and bad people. What does having a piece of paper on the wall that we can point to change about that? We just +b you from the IRC channel and remove you from the GitHub organization and mailing list? That's all the "teeth" that we could possibly have, and it increases administrative burden of the organization (which we already kinda have problems with).

**Comment by urbanslug** [comment]
Then what would have us decide that this or that is wrong or worth getting kicked out of the community over? Just common sense?

**Comment by alanorth** [comment]
We have banned people from the IRC channel before, and we don't have a code
of conduct. Like I said, with and without a code of conduct there will
still be good people and bad people. What good does writing down "don't be
a jerk" do?

On Fri, Jul 1, 2016, 15:19 Njagi Mwaniki <notifications@github.com> wrote:

> Then what would have us decide that this or that is wrong or worth getting
> kicked out of the community over? Just common sense?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/nairobilug/nairobilug.or.ke/pull/157#issuecomment-229932609>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AALtClSZeJilv5eqB_RQT_hhjG6vv0Zfks5qRQXOgaJpZM4JCaZ6>
> .
>
-- 

Alan Orth
alan.orth@gmail.com
https://englishbulgaria.net
https://alaninkenya.org
https://mjanja.ch

**Comment by urbanslug** [comment]
I don't feel strongly on the matter so I'm cool with whatever you guys choose.

**Comment by Muriukidavid** [comment]
Joining the LUG (and  staying) is mostly driven by personal interest rather than comfort of knowing there's protection from harassment, prejudice, disrespect, whatever else is out there... I don't personally think it's going to make a difference. Or do we have occurrences in the past that leads us to set up C.o.C? My two cents.

**Comment by kevthanewversi** [comment]
I vote no too on this. Simpy because we are all adults and not in high school anymore plus writing down CoCs won't change a thing. People are still gonna do what they feel like doing.

**Comment by rwanyoike** [comment]
> C.o.Cs are mostly bullshit. I vote no.

@netivity Lay out some context for me

> That's all the "teeth" that we could possibly have, and it increases administrative burden of the organization 

@alanorth I agree, and that's something we need to work on

> What good does writing down "don't be a jerk" do?

@alanorth a reference, rather than leaving it to "common sense"
 
> Or do we have occurrences in the past that leads us to set up C.o.C?

@muriukidavid Our mailing list is quite the case study ;)

> People are still gonna do what they feel like doing.

@kevthanewversi Not unless there's support for the CoC

**Comment by rwanyoike** [comment]
Most comments here lean against having a CoC, with the idea that it's not going to make a difference, "assholes will be assholes, right?", and there is nothing anyone can do about it. 

I think it's easy to think that when you're already part of the LUG, and are used to _the_ assholes <3. But throw in a few strangers, and things start to go off the rails. Especially for the strangers (unless, they're assholes too)

That said, my main argument for a CoC is for newcomers. For people with different backgrounds, levels of confidence etc; _experiences and stereotypes may block them from giving the LUG a chance_. 

Some edge case examples (forgive the stereotyping): the beginner who fears bullying, the girl who sees a boys club, the disabled who feels embarrassed... A CoC can overcome such hesitance. I'm going to steal this from https://twitter.com/lady_nerd

> This isn’t a marketing tool or propaganda. It is the statement that lets your attendees know they have the right to be safe at your event and tells them to to get help if it all goes wrong.**.

Notably, with more and more people attending meetups, we're no longer that small group of 'friends' the LUG started off as. Thanks for participating, 6/278 members ;)

**Comment by jasonrogena** [comment]
Now that we have a channel on Telegram 😅 (that might be much more prone to noise, and probably harder to moderate); don't you think we should at least put up a page explaining what can/can't be posted there and what actions will be taken if posted content is not 'up to spec'?

**Comment by rwanyoike** [comment]
^^ @poppingtonic you were suggesting?

**Comment by poppingtonic** [comment]
@rwanyoike The suggestion is sound.

**Comment by kevthanewversi** [comment]
We have a telegram channel? Link please guys...?


Regards,
Kevin M. Mbarua
0702672922
stackoverflow: kevthanewversi
<http://stackoverflow.com/users/3469960/kevthanewversi>
linkedin: kevin murimi <http://ke.linkedin.com/in/kevinmurimi>
github: kevthanewversi <http://github.com/kevthanewversi>
twitter: kevthanewversi <http://twitter.com/kevthanewversi>

**Comment by bkmgit** [comment]
A code of conduct and/or aims and purpose of the group may be helpful.

**Comment by bkmgit** [comment]
Maybe worth discussing contents at meeting.

**Comment by BonfaceKilz** [comment]
What about having a draft, and then discussing that during a meeting. I
want to sit down and come up with one based on the things shared above.
Wdyt?

-- 
Bonface M. K.
One Divine Emacs To Rule Them All
https://www.bonfacemunyoki.com

**Comment by BonfaceKilz** [comment]
I called for a vote here: https://groups.google.com/g/nairobi-gnu/c/szM2BpWwJ5M and only 2 people voted.  As such I'm going ahead to merge this.  Also,  later I'll create a separate MD off this and add to the repo's root as a standalone root.  FWIW, I prefer this to: https://github.com/nairobilug/nairobilug.or.ke/pull/183/files since it's more encompassing.  Should enough people complain, we'll just revert this commit!

**Pull request closed without merging**
