### PR TITLE
Add 'Glow on GNU, gnu on' svg logo and favicons ; Add G+ link

### PR DESCRIPTION
**Pull request by highPriestLOL**
Attempt at a scalable logo for LUG. The current one is themed as solarize though it can be tweaked and themed however. The repo for different version and raw vectors is https://github.com/nairobilug/lug-logolatte. Cheers

### CODE REVIEW

**Comment by highPriestLOL** [comment]
Someone review this pull-request. Whilst merging this #88, seems like my pull-request #86 also got merged, not sure how o_O. How it went down

```
git checkout -b alanorth-nginx-maps master
git pull https://github.com/alanorth/nairobilug.or.ke.git nginx-maps

git submodule init
git submodule update

git merge --no-ff alanorth-nginx-maps
git push origin master
git push upstream
```
Let me attempt to re-open the pull-request...

**Comment by alanorth** [comment]
Ah, you checked out one of my branches explicitly and merged it into yours. Then, when you merged *your* pull request both mine and yours went to Nairobi LUG's master. In this case it's fine, because my blog post was fine, I was just waiting for someone to check and merge it.  In the future, just make sure your pull requests are rebased on top of nairobulug's master branch.

Oh, and don't use `git pull`. :)  I always do a `git remote update` and then a `git merge origin/master`.  It's a bit like the difference between `apt-get update` and `apt-get upgrade`, the update only updates the indexes, and the upgrade actually downloads and installs them.  `git pull` updates the remotes and then merges them locally, in one command, which is really confusing for most people.

**Comment by highPriestLOL** [comment]
Great insight @alanorth, thank you. Cool beans, a times I wonder if I'll ever figure out git :), seriously there should be a course on git with a proper course outline.

**Comment by alanorth** [comment]
No problem.  You're learning the only way you can: by practice! Use it for all your personal projects, documentation, etc... and you'll get it down in no time!

**Pull request merged**
