### PR TITLE
Update list of Kenya cloud hosting providers

### PR DESCRIPTION
**Pull request by BonfaceKilz**
There were 2 duplicate posts and running `make html` generated:

```
pelican /home/bonface/projects/oqo-nairobilug.or.ke/content -o /home/bonface/projects/oqo-nairobilug.or.ke/output -s /home/bonface/projects/oqo-nairobilug.or.ke/pelicanconf.py
ERROR: Skipping ./hosting-kenya.md: could not find information about 'title'
Done: Processed 48 articles, 0 drafts, 6 pages and 0 hidden pages in 2.00 seconds.
```

As such, I just merged the 2 articles and also updated the timestamp.

### CODE REVIEW

**Comment by BonfaceKilz** [comment]
@bkmgit could you have a look at this.  Should this be OK with you, would you mind if I Acked you in the commit messages before merging?

**Comment by bkmgit** [comment]
Some updates are needed.  Not all the cloud providers have physical servers in Kenya, some may do support from Kenya, but use datacenters outside Kenya.

**Comment by BonfaceKilz** [comment]
Benson Muite ***@***.***> aliandika:

> Some updates are needed.

Ah I see.  I'll try looking into this next week.

> Not all the cloud providers have physical servers in Kenya, some may do support from Kenya, but use datacenters outside Kenya.

TIL!

-- 
(Life is like a pencil that will surely run out,
    but will leave the beautiful writing of life.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Comment by BonfaceKilz** [comment]
Long overdue, but also merging this.

**Pull request merged**
