### PR TITLE
Add a blog post on mounting partitions using systemd

### PR DESCRIPTION
**Pull request by oguya**

### CODE REVIEW

**Comment by alanorth** [comment]
Merged, but corrected Systemd to systemd.

**Comment by alanorth** [comment]
Also, a recommendation to use `$` in your code snippets that are from shell prompts; it's a good visual cue that the snippet is a shell session. Similarly, I usually leave off my username / machine name, as it's irrelevant and also opsec fail for Mossad.

**Comment by urbanslug** [comment]
hahaha the opsec fail for Mossad is funny. Looks like an interesting post.

**Comment by alanorth** [comment]
Yeah, people should share more, like when they fix their sound, learn about bind mounts, etc!

**Comment by urbanslug** [comment]
@alanorth lol plus I'm preparing an emacs cheatsheet. Posting it here will likely help. Not many people around are using emacs and my blog has like zero SEO.

**Comment by oguya** [comment]
@urbanslug blog all teh tings!!!

**Comment by alanorth** [comment]
Not how I always prefer my blog, writing there first and then linking to it
from the LUG post. Cuz I will actually pay for my domain and make sure it's
around for a long, long time, but I can't trust all y'all cuz you're a
bunch of busters!

Alan

On Tue, Sep 22, 2015 at 4:48 PM, James Oguya <notifications@github.com>
wrote:

> @urbanslug <https://github.com/urbanslug> blog all teh tings!!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nairobilug/nairobilug.or.ke/pull/137#issuecomment-142294445>
> .
>



-- 
Alan Orth
alan.orth@gmail.com
https://alaninkenya.org
https://mjanja.ch
"In heaven all the interesting people are missing." -Friedrich Nietzsche
GPG public key ID: 0x8cb0d0acb5cd81ec209c6cdfbd1a0e09c2f836c0

**Pull request closed without merging**
